name: @name@
version: @version@
author: LyraMS
main: @mainClass@
softdepend: [ MYSlots, LuckyInjector, KtLoader ]

commands:
  luckyessentials:
    aliases: [ less, ess ]
  chatlock:
    aliases: [ cl ]
  clear:
    aliases: [ ci ]
  ewhitelist:
    aliases: [ ewl, wl, whitelist ]
  feed:
    aliases: [ eat ]
  gamemode:
    aliases: [ gm, gmc, gms, gmsp, gma ]
  give:
    aliases: [ i ]
  playerinfo:
    aliases: [ pinfo ]
  smite:
    aliases: [ thor ]
  teleportall:
    aliases: [ tpall, tpallpos ]
  teleport:
    aliases: [ tp, tppos, tphere, s ]
  troll:
    aliases: [ trolls ]
  editsign:
  enchant:
  explode:
  fakeplace:
  fix:
  fly:
  getpos:
  god:
  heal:
  invsee:
  kickall:
  more:
  nobreak:
  nodamage:
  nohit:
  nointeract:
  nopickup:
  noplace:
  onetap:
  slots:
  speed:
  sudo:
  top:
  fakeop: