package dev.luckynetwork.id.lyrams.objects

import org.bukkit.Material
import org.bukkit.inventory.ItemStack

object IMaterial {

    fun getMaterial(name: String, amount: Int): ItemStack {

        if (Material.getMaterial(name.toUpperCase()) != null)
            return ItemStack(Material.getMaterial(name.toUpperCase()), amount)

        when (name.toUpperCase()) {
            "COBBLE" -> return ItemStack(Material.COBBLESTONE, amount)
            "GRANITE" -> return ItemStack(Material.STONE, amount, 1)
            "POLISHEDGRANITE" -> return ItemStack(Material.STONE, amount, 2)
            "DIROITE" -> return ItemStack(Material.STONE, amount, 3)
            "POLISHEDDIROITE" -> return ItemStack(Material.STONE, amount, 4)
            "ANDESITE" -> return ItemStack(Material.STONE, amount, 5)
            "POLISHEDANDESITE" -> return ItemStack(Material.STONE, amount, 6)
            "ENDSTONE" -> return ItemStack(Material.ENDER_STONE, amount)

            "COARSEDIRT" -> return ItemStack(Material.DIRT, amount, 1)
            "PODZOL" -> return ItemStack(Material.DIRT, amount, 2)

            "OAKWOOD" -> return ItemStack(Material.WOOD, amount)
            "SPRUCEWOOD" -> return ItemStack(Material.WOOD, amount, 1)
            "BIRCHWOOD" -> return ItemStack(Material.WOOD, amount, 2)
            "JUNGLEWOOD" -> return ItemStack(Material.WOOD, amount, 3)
            "ACACIAWOOD" -> return ItemStack(Material.WOOD, amount, 4)
            "DARKOAKWOOD" -> return ItemStack(Material.WOOD, amount, 5)

            "OAKSAPLING" -> return ItemStack(Material.SAPLING, amount)
            "SPRUCESAPLING" -> return ItemStack(Material.SAPLING, amount, 1)
            "BIRCHSAPLING" -> return ItemStack(Material.SAPLING, amount, 2)
            "JUNGLESAPLING" -> return ItemStack(Material.SAPLING, amount, 3)
            "ACACIASAPLING" -> return ItemStack(Material.SAPLING, amount, 4)
            "DARKOAKSAPLING" -> return ItemStack(Material.SAPLING, amount, 5)

            "TRAPDOOR" -> return ItemStack(Material.TRAP_DOOR, amount)
            "IRONTRAPDOOR" -> return ItemStack(Material.IRON_TRAPDOOR, amount)

            "DOOR" -> return ItemStack(Material.WOODEN_DOOR, amount)
            "IRONDOOR" -> return ItemStack(Material.IRON_DOOR, amount)
            "SPRUCEDOOR" -> return ItemStack(Material.SPRUCE_DOOR_ITEM, amount)
            "BIRCHDOOR" -> return ItemStack(Material.BIRCH_DOOR_ITEM, amount)
            "JUNGLEDOOR" -> return ItemStack(Material.JUNGLE_DOOR_ITEM, amount)
            "ACACIADOOR" -> return ItemStack(Material.ACACIA_DOOR_ITEM, amount)
            "DARKOAKDOOR" -> return ItemStack(Material.DARK_OAK_DOOR_ITEM, amount)

            "REDSAND" -> return ItemStack(Material.SAND, amount, 1)
            "SOULSAND" -> return ItemStack(Material.SOUL_SAND, amount)

            "GOLDINGOT" -> return ItemStack(Material.GOLD_INGOT, amount)
            "IRONINGOT" -> return ItemStack(Material.IRON_INGOT, amount)

            "GOLDORE" -> return ItemStack(Material.GOLD_ORE, amount)
            "IRONORE" -> return ItemStack(Material.IRON_ORE, amount)
            "COALORE" -> return ItemStack(Material.COAL_ORE, amount)
            "LAPISORE" -> return ItemStack(Material.LAPIS_ORE, amount)
            "DIAMONDORE" -> return ItemStack(Material.DIAMOND_ORE, amount)
            "REDSTONEORE" -> return ItemStack(Material.REDSTONE_ORE, amount)
            "EMERALDORE" -> return ItemStack(Material.EMERALD_ORE, amount)
            "QUARTZORE" -> return ItemStack(Material.QUARTZ_ORE, amount)

            "GOLDBLOCK" -> return ItemStack(Material.GOLD_BLOCK, amount)
            "IRONBLOCK" -> return ItemStack(Material.IRON_BLOCK, amount)
            "COALBLOCK" -> return ItemStack(Material.COAL_BLOCK, amount)
            "LAPISBLOCK" -> return ItemStack(Material.LAPIS_BLOCK, amount)
            "DIAMONDBLOCK" -> return ItemStack(Material.DIAMOND_BLOCK, amount)
            "REDSTONEBLOCK" -> return ItemStack(Material.REDSTONE_BLOCK, amount)
            "EMERALDBLOCK" -> return ItemStack(Material.EMERALD_BLOCK, amount)

            "OAKLOG" -> return ItemStack(Material.LOG, amount)
            "SPRUCELOG" -> return ItemStack(Material.LOG, amount, 1)
            "BIRCHLOG" -> return ItemStack(Material.LOG, amount, 2)
            "JUNGLELOG" -> return ItemStack(Material.LOG, amount, 3)
            "ACACIALOG" -> return ItemStack(Material.LOG, amount, 4)
            "DARKOAKLOG" -> return ItemStack(Material.LOG, amount, 5)

            "OAKLEAVES" -> return ItemStack(Material.LEAVES, amount)
            "SPRUCELEAVES" -> return ItemStack(Material.LEAVES, amount, 1)
            "BIRCHLEAVES" -> return ItemStack(Material.LEAVES, amount, 2)
            "JUNGLELEAVES" -> return ItemStack(Material.LEAVES, amount, 3)
            "ACACIALEAVES" -> return ItemStack(Material.LEAVES, amount, 4)
            "DARKOAKLEAVES" -> return ItemStack(Material.LEAVES, amount, 5)

            "CHISELEDSANDSTONE" -> return ItemStack(Material.SANDSTONE, amount, 1)
            "SMOOTHSANDSTONE" -> return ItemStack(Material.SANDSTONE, amount, 2)

            "POWEREDRAIL" -> return ItemStack(Material.POWERED_RAIL, amount)
            "DETECTORRAIL" -> return ItemStack(Material.DETECTOR_RAIL, amount)

            "ORANGEWOOL" -> return ItemStack(Material.WOOL, amount, 1)
            "MAGENTAWOOL" -> return ItemStack(Material.WOOL, amount, 2)
            "LIGHTBLUEWOOL" -> return ItemStack(Material.WOOL, amount, 3)
            "YELLOWWOOL" -> return ItemStack(Material.WOOL, amount, 4)
            "LIMEWOOL" -> return ItemStack(Material.WOOL, amount, 5)
            "PINKWOOL" -> return ItemStack(Material.WOOL, amount, 6)
            "GRAYWOOL" -> return ItemStack(Material.WOOL, amount, 7)
            "LIGHTGRAYWOOL" -> return ItemStack(Material.WOOL, amount, 8)
            "CYANWOOL" -> return ItemStack(Material.WOOL, amount, 9)
            "PURPLEWOOL" -> return ItemStack(Material.WOOL, amount, 10)
            "BLUEWOOL" -> return ItemStack(Material.WOOL, amount, 11)
            "BROWNWOOL" -> return ItemStack(Material.WOOL, amount, 12)
            "GREENWOOL" -> return ItemStack(Material.WOOL, amount, 13)
            "REDWOOL" -> return ItemStack(Material.WOOL, amount, 14)
            "BLACKWOOL" -> return ItemStack(Material.WOOL, amount, 15)

            "ORANGECARPET" -> return ItemStack(Material.CARPET, amount, 1)
            "MAGENTACARPET" -> return ItemStack(Material.CARPET, amount, 2)
            "LIGHTBLUECARPET" -> return ItemStack(Material.CARPET, amount, 3)
            "YELLOWCARPET" -> return ItemStack(Material.CARPET, amount, 4)
            "LIMECARPET" -> return ItemStack(Material.CARPET, amount, 5)
            "PINKCARPET" -> return ItemStack(Material.CARPET, amount, 6)
            "GRAYCARPET" -> return ItemStack(Material.CARPET, amount, 7)
            "LIGHTGRAYCARPET" -> return ItemStack(Material.CARPET, amount, 8)
            "CYANCARPET" -> return ItemStack(Material.CARPET, amount, 9)
            "PURPLECARPET" -> return ItemStack(Material.CARPET, amount, 10)
            "BLUECARPET" -> return ItemStack(Material.CARPET, amount, 11)
            "BROWNCARPET" -> return ItemStack(Material.CARPET, amount, 12)
            "GREENCARPET" -> return ItemStack(Material.CARPET, amount, 13)
            "REDCARPET" -> return ItemStack(Material.CARPET, amount, 14)
            "BLACKCARPET" -> return ItemStack(Material.CARPET, amount, 15)

            "WHITEBANNER" -> return ItemStack(Material.BANNER, amount, 15)
            "ORANGEBANNER" -> return ItemStack(Material.BANNER, amount, 14)
            "MAGENTABANNER" -> return ItemStack(Material.BANNER, amount, 13)
            "LIGHTBLUEBANNER" -> return ItemStack(Material.BANNER, amount, 12)
            "YELLOWBANNER" -> return ItemStack(Material.BANNER, amount, 11)
            "LIMEBANNER" -> return ItemStack(Material.BANNER, amount, 10)
            "PINKBANNER" -> return ItemStack(Material.BANNER, amount, 9)
            "GRAYBANNER" -> return ItemStack(Material.BANNER, amount, 8)
            "LIGHTGRAYBANNER" -> return ItemStack(Material.BANNER, amount, 7)
            "CYANBANNER" -> return ItemStack(Material.BANNER, amount, 6)
            "PURPLEBANNER" -> return ItemStack(Material.BANNER, amount, 5)
            "BLUEBANNER" -> return ItemStack(Material.BANNER, amount, 4)
            "BROWNBANNER" -> return ItemStack(Material.BANNER, amount, 3)
            "GREENBANNER" -> return ItemStack(Material.BANNER, amount, 2)
            "REDBANNER" -> return ItemStack(Material.BANNER, amount, 1)
            "BLACKBANNER" -> return ItemStack(Material.BANNER, amount)

            "WHITESTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 0)
            "ORANGESTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 1)
            "MAGENTASTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 2)
            "LIGHTBLUESTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 3)
            "YELLOWSTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 4)
            "LIMESTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 5)
            "PINKSTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 6)
            "GRAYSTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 7)
            "LIGHTGRAYSTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 8)
            "CYANSTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 9)
            "PURPLESTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 10)
            "BLUESTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 11)
            "BROWNSTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 12)
            "GREENSTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 13)
            "REDSTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 14)
            "BLACKSTAINEDGLASS" -> return ItemStack(Material.STAINED_GLASS, amount, 15)

            "GLASSPANE" -> return ItemStack(Material.THIN_GLASS, amount)
            "WHITESTAINEDPANE", "WHITESTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 0)
            "ORANGESTAINEDPANE", "ORANGESTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 1)
            "MAGENTASTAINEDPANE", "MAGENTASTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 2)
            "LIGHTBLUESTAINEDPANE", "LIGHTBLUESTAINEDGLASSPANE" -> return ItemStack(
                Material.STAINED_GLASS_PANE,
                amount,
                3
            )
            "YELLOWSTAINEDPANE", "YELLOWSTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 4)
            "LIMESTAINEDPANE", "LIMESTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 5)
            "PINKSTAINEDPANE", "PINKSTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 6)
            "GRAYSTAINEDPANE", "GRAYSTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 7)
            "LIGHTGRAYSTAINEDPANE", "LIGHTGRAYSTAINEDGLASSPANE" -> return ItemStack(
                Material.STAINED_GLASS_PANE,
                amount,
                8
            )
            "CYANSTAINEDPANE", "CYANSTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 9)
            "PURPLESTAINEDPANE", "PURPLESTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 10)
            "BLUESTAINEDPANE", "BLUESTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 11)
            "BROWNSTAINEDPANE", "BROWNSTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 12)
            "GREENSTAINEDPANE", "GREENSTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 13)
            "REDSTAINEDPANE", "REDSTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 14)
            "BLACKSTAINEDPANE", "BLACKSTAINEDGLASSPANE" -> return ItemStack(Material.STAINED_GLASS_PANE, amount, 15)

            "CLAY" -> return ItemStack(Material.CLAY)
            "HARDCLAY" -> return ItemStack(Material.HARD_CLAY)
            "WHITESTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 0)
            "ORANGESTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 1)
            "MAGENTASTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 2)
            "LIGHTBLUESTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 3)
            "YELLOWSTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 4)
            "LIMESTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 5)
            "PINKSTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 6)
            "GRAYSTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 7)
            "LIGHTGRAYSTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 8)
            "CYANSTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 9)
            "PURPLESTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 10)
            "BLUESTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 11)
            "BROWNSTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 12)
            "GREENSTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 13)
            "REDSTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 14)
            "BLACKSTAINEDCLAY" -> return ItemStack(Material.STAINED_CLAY, amount, 15)

            "DANDELION" -> return ItemStack(Material.YELLOW_FLOWER, amount)
            "POPPY" -> return ItemStack(Material.RED_ROSE, amount)
            "ORCHID", "BLUEORCHID" -> return ItemStack(Material.RED_ROSE, amount, 1)
            "ALLIUM" -> return ItemStack(Material.RED_ROSE, amount, 2)
            "AZURE", "AZUREBLUET" -> return ItemStack(Material.RED_ROSE, amount, 3)
            "TULIP", "REDTULIP" -> return ItemStack(Material.RED_ROSE, amount, 4)
            "ORANGETULIP" -> return ItemStack(Material.RED_ROSE, amount, 5)
            "WHITETULIP" -> return ItemStack(Material.RED_ROSE, amount, 6)
            "PINKTULIP" -> return ItemStack(Material.RED_ROSE, amount, 7)
            "DAISY", "OXYEDAISY" -> return ItemStack(Material.RED_ROSE, amount, 8)

            "SLAB", "STONESLAB" -> return ItemStack(Material.STONE_SLAB2, amount)
            "SANDSTONESLAB" -> return ItemStack(Material.STONE_SLAB2, amount, 1)
            "COBBLESLAB", "COBBLESTONESLAB" -> return ItemStack(Material.STONE_SLAB2, amount, 3)
            "BRICKSLAB" -> return ItemStack(Material.STONE_SLAB2, amount, 4)
            "STONEBRICKSLAB" -> return ItemStack(Material.STONE_SLAB2, amount, 5)
            "NETHERBRICKSLAB", "NETHERSLAB" -> return ItemStack(Material.STONE_SLAB2, amount, 6)
            "QUARTZSLAB" -> return ItemStack(Material.STONE_SLAB2, amount, 7)

            "OAKSTAIRS" -> return ItemStack(Material.WOOD_STAIRS, amount)
            "COBBLESTAIRS" -> return ItemStack(Material.COBBLESTONE_STAIRS, amount)
            "BRICKSTAIRS" -> return ItemStack(Material.BRICK_STAIRS, amount)
            "STONEBRICKSTAIRS" -> return ItemStack(Material.SMOOTH_STAIRS, amount)
            "NETHERBRICKSTAIRS" -> return ItemStack(Material.NETHER_BRICK_STAIRS, amount)
            "SPRUCESTAIRS" -> return ItemStack(Material.SPRUCE_WOOD_STAIRS, amount)
            "BIRCHSTAIRS" -> return ItemStack(Material.BIRCH_WOOD_STAIRS, amount)
            "JUNGLESTAIRS" -> return ItemStack(Material.JUNGLE_WOOD_STAIRS, amount)
            "QUARTZSTAIRS" -> return ItemStack(Material.QUARTZ_STAIRS, amount)
            "ACACIASTAIRS" -> return ItemStack(Material.ACACIA_STAIRS, amount)
            "DARKOAKSTAIRS" -> return ItemStack(Material.DARK_OAK_STAIRS, amount)
            "REDSANDSTONESTAIRS" -> return ItemStack(Material.RED_SANDSTONE_STAIRS, amount)

            "STONEBUTTON" -> return ItemStack(Material.STONE_BUTTON, amount)
            "WOODBUTTON" -> return ItemStack(Material.WOOD_BUTTON, amount)

            "STONEPRESUREPLATE", "STONEPLATE" -> return ItemStack(Material.STONE_PLATE, amount)
            "WOODPRESUREPLATE", "WOODPLATE" -> return ItemStack(Material.WOOD_PLATE, amount)
            "GOLDPRESUREPLATE", "GOLDPLATE" -> return ItemStack(Material.GOLD_PLATE, amount)
            "IRONPRESUREPLATE", "IRONPLATE" -> return ItemStack(Material.IRON_PLATE, amount)

            "QUARTZBLOCK" -> return ItemStack(Material.QUARTZ_BLOCK, amount)
            "CHISLEDQUARTZBLOCK" -> return ItemStack(Material.QUARTZ_BLOCK, amount, 1)
            "PILLARQUARTZBLOCK" -> return ItemStack(Material.QUARTZ_BLOCK, amount, 2)


            // combat
            "DIAMONDSWORD" -> return ItemStack(Material.DIAMOND_SWORD, amount)
            "GOLDENDSWORD", "GOLDSWORD" -> return ItemStack(Material.GOLD_SWORD, amount)
            "IRONSWORD" -> return ItemStack(Material.IRON_SWORD, amount)
            "STONESWORD" -> return ItemStack(Material.STONE_SWORD, amount)
            "WOODSWORD", "WOODENSWORD" -> return ItemStack(Material.WOOD_SWORD, amount)

            "DIAMONDAXE" -> return ItemStack(Material.DIAMOND_AXE, amount)
            "GOLDENDAXE", "GOLDAXE" -> return ItemStack(Material.GOLD_AXE, amount)
            "IRONAXE" -> return ItemStack(Material.IRON_AXE, amount)
            "STONEAXE" -> return ItemStack(Material.STONE_AXE, amount)
            "WOODAXE", "WOODENAXE" -> return ItemStack(Material.WOOD_AXE, amount)

            "DIAMONDPICKAXE" -> return ItemStack(Material.DIAMOND_PICKAXE, amount)
            "GOLDENDPICKAXE", "GOLDPICKAXE" -> return ItemStack(Material.GOLD_PICKAXE, amount)
            "IRONPICKAXE" -> return ItemStack(Material.IRON_PICKAXE, amount)
            "STONEPICKAXE" -> return ItemStack(Material.STONE_PICKAXE, amount)
            "WOODPICKAXE", "WOODENPICKAXE" -> return ItemStack(Material.WOOD_PICKAXE, amount)

            "DIAMONDSHOVEL" -> return ItemStack(Material.DIAMOND_SPADE, amount)
            "GOLDENDSHOVEL", "GOLDSHOVEL" -> return ItemStack(Material.GOLD_SPADE, amount)
            "IRONSHOVEL" -> return ItemStack(Material.IRON_SPADE, amount)
            "STONESHOVEL" -> return ItemStack(Material.STONE_SPADE, amount)
            "WOODSHOVEL", "WOODENSHOVEL" -> return ItemStack(Material.WOOD_SPADE, amount)

            "DIAMONDHOE" -> return ItemStack(Material.DIAMOND_HOE, amount)
            "GOLDENDHOE", "GOLDHOE" -> return ItemStack(Material.GOLD_HOE, amount)
            "IRONHOE" -> return ItemStack(Material.IRON_HOE, amount)
            "STONEHOE" -> return ItemStack(Material.STONE_HOE, amount)
            "WOODHOE", "WOODENHOE" -> return ItemStack(Material.WOOD_HOE, amount)

            "LEATHERHELMET" -> return ItemStack(Material.LEATHER_HELMET, amount)
            "LEATHERCHESTPLATE" -> return ItemStack(Material.LEATHER_CHESTPLATE, amount)
            "LEATHERLEGGINGS" -> return ItemStack(Material.LEATHER_LEGGINGS, amount)
            "LEATHERBOOTS" -> return ItemStack(Material.LEATHER_BOOTS, amount)

            "GOLDHELMET", "GOLDENHELMET" -> return ItemStack(Material.GOLD_HELMET, amount)
            "GOLDCHESTPLATE", "GOLDENCHESTPLATE" -> return ItemStack(Material.GOLD_CHESTPLATE, amount)
            "GOLDLEGGINGS", "GOLDENLEGGINGS" -> return ItemStack(Material.GOLD_LEGGINGS, amount)
            "GOLDBOOTS", "GOLDENBOOTS" -> return ItemStack(Material.GOLD_BOOTS, amount)

            "IRONHELMET" -> return ItemStack(Material.IRON_HELMET, amount)
            "IRONCHESTPLATE" -> return ItemStack(Material.IRON_CHESTPLATE, amount)
            "IRONLEGGINGS" -> return ItemStack(Material.IRON_LEGGINGS, amount)
            "IRONBOOTS" -> return ItemStack(Material.IRON_BOOTS, amount)

            "CHAINMAILHELMET", "CHAINHELMET" -> return ItemStack(Material.CHAINMAIL_HELMET, amount)
            "CHAINMAILCHESTPLATE", "CHAINCHESTPLATE" -> return ItemStack(Material.CHAINMAIL_CHESTPLATE, amount)
            "CHAINMAILLEGGINGS", "CHAINLEGGINGS" -> return ItemStack(Material.CHAINMAIL_LEGGINGS, amount)
            "CHAINMAILBOOTS", "CHAINBOOTS" -> return ItemStack(Material.CHAINMAIL_BOOTS, amount)

            "DIAMONDHELMET" -> return ItemStack(Material.DIAMOND_HELMET, amount)
            "DIAMONDCHESTPLATE" -> return ItemStack(Material.DIAMOND_CHESTPLATE, amount)
            "DIAMONDLEGGINGS" -> return ItemStack(Material.DIAMOND_LEGGINGS, amount)
            "DIAMONDBOOTS" -> return ItemStack(Material.DIAMOND_BOOTS, amount)

            // food stuff
            "GOLDAPPLE", "GOLDENAPPLE" -> return ItemStack(Material.GOLDEN_APPLE, amount)
            "GODAPPLE", "NOTCHAPPLE" -> return ItemStack(Material.GOLDEN_APPLE, amount, 1)
            "RAWBEEF", "BEEF", "RAWMEAT", "MEAT" -> return ItemStack(Material.RAW_BEEF, amount)
            "STEAK", "COOKEDBEEF", "COOKEDMEAT" -> return ItemStack(Material.COOKED_BEEF, amount)
            "PORKCHOP" -> return ItemStack(Material.PORK, amount)
            "COOKEDPORKCHOP" -> return ItemStack(Material.GRILLED_PORK, amount)
            "RAWMUTTON" -> return ItemStack(Material.MUTTON, amount)
            "COOKEDMUTTON" -> return ItemStack(Material.COOKED_MUTTON, amount)
            "RAWRABBIT" -> return ItemStack(Material.RABBIT, amount)
            "COOKEDRABBIT" -> return ItemStack(Material.COOKED_RABBIT, amount)
            "FISH" -> return ItemStack(Material.RAW_FISH, amount)
            "SALMON" -> return ItemStack(Material.RAW_FISH, amount, 1)
            "CLOWNFISH", "NEMO" -> return ItemStack(Material.RAW_FISH, amount, 2)
            "PUFFERFISH" -> return ItemStack(Material.RAW_FISH, amount, 3)
            "COOKEDFISH" -> return ItemStack(Material.COOKED_FISH, amount)
            "COOKEDSALMON" -> return ItemStack(Material.COOKED_FISH, amount, 1)
            "BAKEDPOTATO" -> return ItemStack(Material.BAKED_POTATO, amount)
            "POISONEDPOTATO", "POSIONPOTATO" -> return ItemStack(Material.POISONOUS_POTATO, amount)
            "SPIDEREYE" -> return ItemStack(Material.SPIDER_EYE, amount)

            // bucket
            "WATER", "WATERBUCKET" -> return ItemStack(Material.WATER_BUCKET, amount)
            "LAVA", "LAVABUCKET" -> return ItemStack(Material.LAVA_BUCKET, amount)


            // misc
            "MUSHROOM", "REDMUSHROOM" -> return ItemStack(Material.RED_MUSHROOM, amount)
            "BROWNMUSHROOM" -> return ItemStack(Material.BROWN_MUSHROOM, amount)
            "MOSSSTONE" -> return ItemStack(Material.MOSSY_COBBLESTONE, amount)
            "CRAFTINGTABLE" -> return ItemStack(Material.WORKBENCH, amount)
            "PEARL", "ENDERPEARL" -> return ItemStack(Material.ENDER_PEARL, amount)
            "LILLYPAD", "LILLY" -> return ItemStack(Material.WATER_LILY, amount)
            "SNOW" -> return ItemStack(Material.SNOW_BLOCK, amount)
            "SNOWBALL" -> return ItemStack(Material.SNOW_BALL, amount)
            "CLAYBALL" -> return ItemStack(Material.CLAY_BALL, amount)
            "MELON" -> return ItemStack(Material.MELON_BLOCK, amount)
            "ENCHANTTABLE" -> return ItemStack(Material.ENCHANTMENT_TABLE, amount)
            "ENDPORTAL" -> return ItemStack(Material.ENDER_PORTAL_FRAME, amount)
            "ENDERCHEST" -> return ItemStack(Material.ENDER_CHEST, amount)
            "TRAPPEDCHEST" -> return ItemStack(Material.TRAPPED_CHEST, amount)
            "NETHERSTAR" -> return ItemStack(Material.NETHER_STAR, amount)
            "TRIPWIRE", "TRIPWIREHOOK" -> return ItemStack(Material.TRIPWIRE_HOOK, amount)
            "STICKYPISTON" -> return ItemStack(Material.PISTON_STICKY_BASE, amount)
            "COBWEB" -> return ItemStack(Material.WEB, amount)
            "NAMETAG" -> return ItemStack(Material.NAME_TAG, amount)
            "FLINTANDSTEEL", "FLINTSTEEL", "LIGHTER" -> return ItemStack(Material.FLINT_AND_STEEL, amount)
            "FISHINGROD", "ROD" -> return ItemStack(Material.FISHING_ROD, amount)
            "WETSPONGE" -> return ItemStack(Material.SPONGE, amount, 1)
            "LAPIS", "LAPISLAZULI" -> return ItemStack(Material.INK_SACK, amount, 4)

            else -> return ItemStack(Material.AIR)
        }
    }

}