package dev.luckynetwork.id.lyrams.enums

import org.bukkit.Material
import org.bukkit.inventory.ItemStack

@Suppress("unused", "SpellCheckingInspection")
enum class XItemStack(private val itemStack: ItemStack) {

    COBBLE(ItemStack(Material.COBBLESTONE, 1)),
    STONEBRICK(ItemStack(Material.SMOOTH_BRICK, 1)),
    GRANITE(ItemStack(Material.STONE, 1, 1)),
    POLISHEDGRANITE(ItemStack(Material.STONE, 1, 2)),
    DIROITE(ItemStack(Material.STONE, 1, 3)),
    POLISHEDDIROITE(ItemStack(Material.STONE, 1, 4)),
    ANDESITE(ItemStack(Material.STONE, 1, 5)),
    POLISHEDANDESITE(ItemStack(Material.STONE, 1, 6)),
    ENDSTONE(ItemStack(Material.ENDER_STONE, 1)),

    COARSEDIRT(ItemStack(Material.DIRT, 1, 1)),
    PODZOL(ItemStack(Material.DIRT, 1, 2)),

    OAKWOOD(ItemStack(Material.WOOD, 1)),
    SPRUCEWOOD(ItemStack(Material.WOOD, 1, 1)),
    BIRCHWOOD(ItemStack(Material.WOOD, 1, 2)),
    JUNGLEWOOD(ItemStack(Material.WOOD, 1, 3)),
    ACACIAWOOD(ItemStack(Material.WOOD, 1, 4)),
    DARKOAKWOOD(ItemStack(Material.WOOD, 1, 5)),

    OAKSAPLING(ItemStack(Material.SAPLING, 1)),
    SPRUCESAPLING(ItemStack(Material.SAPLING, 1, 1)),
    BIRCHSAPLING(ItemStack(Material.SAPLING, 1, 2)),
    JUNGLESAPLING(ItemStack(Material.SAPLING, 1, 3)),
    ACACIASAPLING(ItemStack(Material.SAPLING, 1, 4)),
    DARKOAKSAPLING(ItemStack(Material.SAPLING, 1, 5)),

    TRAPDOOR(ItemStack(Material.TRAP_DOOR, 1)),
    IRONTRAPDOOR(ItemStack(Material.IRON_TRAPDOOR, 1)),

    DOOR(ItemStack(Material.WOODEN_DOOR, 1)),
    IRONDOOR(ItemStack(Material.IRON_DOOR, 1)),
    SPRUCEDOOR(ItemStack(Material.SPRUCE_DOOR_ITEM, 1)),
    BIRCHDOOR(ItemStack(Material.BIRCH_DOOR_ITEM, 1)),
    JUNGLEDOOR(ItemStack(Material.JUNGLE_DOOR_ITEM, 1)),
    ACACIADOOR(ItemStack(Material.ACACIA_DOOR_ITEM, 1)),
    DARKOAKDOOR(ItemStack(Material.DARK_OAK_DOOR_ITEM, 1)),

    IRONBAR(ItemStack(Material.IRON_BARDING, 1)),
    BARDING(ItemStack(Material.IRON_BARDING, 1)),
    BAR(ItemStack(Material.IRON_BARDING, 1)),

    REDSAND(ItemStack(Material.SAND, 1, 1)),
    SOULSAND(ItemStack(Material.SOUL_SAND, 1)),

    GOLDINGOT(ItemStack(Material.GOLD_INGOT, 1)),
    IRONINGOT(ItemStack(Material.IRON_INGOT, 1)),

    GOLDORE(ItemStack(Material.GOLD_ORE, 1)),
    IRONORE(ItemStack(Material.IRON_ORE, 1)),
    COALORE(ItemStack(Material.COAL_ORE, 1)),
    LAPISORE(ItemStack(Material.LAPIS_ORE, 1)),
    DIAMONDORE(ItemStack(Material.DIAMOND_ORE, 1)),
    REDSTONEORE(ItemStack(Material.REDSTONE_ORE, 1)),
    EMERALDORE(ItemStack(Material.EMERALD_ORE, 1)),
    QUARTZORE(ItemStack(Material.QUARTZ_ORE, 1)),

    GOLDBLOCK(ItemStack(Material.GOLD_BLOCK, 1)),
    IRONBLOCK(ItemStack(Material.IRON_BLOCK, 1)),
    COALBLOCK(ItemStack(Material.COAL_BLOCK, 1)),
    LAPISBLOCK(ItemStack(Material.LAPIS_BLOCK, 1)),
    DIAMONDBLOCK(ItemStack(Material.DIAMOND_BLOCK, 1)),
    REDSTONEBLOCK(ItemStack(Material.REDSTONE_BLOCK, 1)),
    EMERALDBLOCK(ItemStack(Material.EMERALD_BLOCK, 1)),

    OAKLOG(ItemStack(Material.LOG, 1)),
    SPRUCELOG(ItemStack(Material.LOG, 1, 1)),
    BIRCHLOG(ItemStack(Material.LOG, 1, 2)),
    JUNGLELOG(ItemStack(Material.LOG, 1, 3)),
    ACACIALOG(ItemStack(Material.LOG, 1, 4)),
    DARKOAKLOG(ItemStack(Material.LOG, 1, 5)),

    OAKLEAVES(ItemStack(Material.LEAVES, 1)),
    OAKLEAF(ItemStack(Material.LEAVES, 1)),
    SPRUCELEAVES(ItemStack(Material.LEAVES, 1, 1)),
    SPRUCELEAF(ItemStack(Material.LEAVES, 1, 1)),
    BIRCHLEAVES(ItemStack(Material.LEAVES, 1, 2)),
    BIRCHLEAF(ItemStack(Material.LEAVES, 1, 2)),
    JUNGLELEAVES(ItemStack(Material.LEAVES, 1, 3)),
    JUNGLELEAF(ItemStack(Material.LEAVES, 1, 3)),
    ACACIALEAVES(ItemStack(Material.LEAVES, 1, 4)),
    ACACIALEAF(ItemStack(Material.LEAVES, 1, 4)),
    DARKOAKLEAVES(ItemStack(Material.LEAVES, 1, 5)),
    DARKOAKLEAF(ItemStack(Material.LEAVES, 1, 5)),

    CHISELEDSANDSTONE(ItemStack(Material.SANDSTONE, 1, 1)),
    SMOOTHSANDSTONE(ItemStack(Material.SANDSTONE, 1, 2)),

    POWEREDRAIL(ItemStack(Material.POWERED_RAIL, 1)),
    DETECTORRAIL(ItemStack(Material.DETECTOR_RAIL, 1)),

    ORANGEWOOL(ItemStack(Material.WOOL, 1, 1)),
    MAGENTAWOOL(ItemStack(Material.WOOL, 1, 2)),
    LIGHTBLUEWOOL(ItemStack(Material.WOOL, 1, 3)),
    YELLOWWOOL(ItemStack(Material.WOOL, 1, 4)),
    LIMEWOOL(ItemStack(Material.WOOL, 1, 5)),
    PINKWOOL(ItemStack(Material.WOOL, 1, 6)),
    GRAYWOOL(ItemStack(Material.WOOL, 1, 7)),
    LIGHTGRAYWOOL(ItemStack(Material.WOOL, 1, 8)),
    CYANWOOL(ItemStack(Material.WOOL, 1, 9)),
    PURPLEWOOL(ItemStack(Material.WOOL, 1, 10)),
    BLUEWOOL(ItemStack(Material.WOOL, 1, 11)),
    BROWNWOOL(ItemStack(Material.WOOL, 1, 12)),
    GREENWOOL(ItemStack(Material.WOOL, 1, 13)),
    REDWOOL(ItemStack(Material.WOOL, 1, 14)),
    BLACKWOOL(ItemStack(Material.WOOL, 1, 15)),

    ORANGECARPET(ItemStack(Material.CARPET, 1, 1)),
    MAGENTACARPET(ItemStack(Material.CARPET, 1, 2)),
    LIGHTBLUECARPET(ItemStack(Material.CARPET, 1, 3)),
    YELLOWCARPET(ItemStack(Material.CARPET, 1, 4)),
    LIMECARPET(ItemStack(Material.CARPET, 1, 5)),
    PINKCARPET(ItemStack(Material.CARPET, 1, 6)),
    GRAYCARPET(ItemStack(Material.CARPET, 1, 7)),
    LIGHTGRAYCARPET(ItemStack(Material.CARPET, 1, 8)),
    CYANCARPET(ItemStack(Material.CARPET, 1, 9)),
    PURPLECARPET(ItemStack(Material.CARPET, 1, 10)),
    BLUECARPET(ItemStack(Material.CARPET, 1, 11)),
    BROWNCARPET(ItemStack(Material.CARPET, 1, 12)),
    GREENCARPET(ItemStack(Material.CARPET, 1, 13)),
    REDCARPET(ItemStack(Material.CARPET, 1, 14)),
    BLACKCARPET(ItemStack(Material.CARPET, 1, 15)),

    WHITEBANNER(ItemStack(Material.BANNER, 1, 15)),
    ORANGEBANNER(ItemStack(Material.BANNER, 1, 14)),
    MAGENTABANNER(ItemStack(Material.BANNER, 1, 13)),
    LIGHTBLUEBANNER(ItemStack(Material.BANNER, 1, 12)),
    YELLOWBANNER(ItemStack(Material.BANNER, 1, 11)),
    LIMEBANNER(ItemStack(Material.BANNER, 1, 10)),
    PINKBANNER(ItemStack(Material.BANNER, 1, 9)),
    GRAYBANNER(ItemStack(Material.BANNER, 1, 8)),
    LIGHTGRAYBANNER(ItemStack(Material.BANNER, 1, 7)),
    CYANBANNER(ItemStack(Material.BANNER, 1, 6)),
    PURPLEBANNER(ItemStack(Material.BANNER, 1, 5)),
    BLUEBANNER(ItemStack(Material.BANNER, 1, 4)),
    BROWNBANNER(ItemStack(Material.BANNER, 1, 3)),
    GREENBANNER(ItemStack(Material.BANNER, 1, 2)),
    REDBANNER(ItemStack(Material.BANNER, 1, 1)),
    BLACKBANNER(ItemStack(Material.BANNER, 1)),

    WHITESTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 0)),
    WHITEGLASS(ItemStack(Material.STAINED_GLASS, 1, 0)),
    ORANGESTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 1)),
    ORANGEGLASS(ItemStack(Material.STAINED_GLASS, 1, 1)),
    MAGENTASTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 2)),
    MAGENTAGLASS(ItemStack(Material.STAINED_GLASS, 1, 2)),
    LIGHTBLUESTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 3)),
    LIGHTBLUEGLASS(ItemStack(Material.STAINED_GLASS, 1, 3)),
    YELLOWSTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 4)),
    YELLOWGLASS(ItemStack(Material.STAINED_GLASS, 1, 4)),
    LIMESTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 5)),
    LIMEGLASS(ItemStack(Material.STAINED_GLASS, 1, 5)),
    PINKSTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 6)),
    PINKGLASS(ItemStack(Material.STAINED_GLASS, 1, 6)),
    GRAYSTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 7)),
    GRAYGLASS(ItemStack(Material.STAINED_GLASS, 1, 7)),
    LIGHTGRAYSTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 8)),
    LIGHTGRAYGLASS(ItemStack(Material.STAINED_GLASS, 1, 8)),
    CYANSTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 9)),
    CYANGLASS(ItemStack(Material.STAINED_GLASS, 1, 9)),
    PURPLESTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 10)),
    PURPLEGLASS(ItemStack(Material.STAINED_GLASS, 1, 10)),
    BLUESTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 11)),
    BLUEGLASS(ItemStack(Material.STAINED_GLASS, 1, 11)),
    BROWNSTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 12)),
    BROWNGLASS(ItemStack(Material.STAINED_GLASS, 1, 12)),
    GREENSTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 13)),
    GREENGLASS(ItemStack(Material.STAINED_GLASS, 1, 13)),
    REDSTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 14)),
    REDGLASS(ItemStack(Material.STAINED_GLASS, 1, 14)),
    BLACKSTAINEDGLASS(ItemStack(Material.STAINED_GLASS, 1, 15)),
    BLACKGLASS(ItemStack(Material.STAINED_GLASS, 1, 15)),

    GLASSPANE(ItemStack(Material.THIN_GLASS, 1)),
    WHITESTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 0)),
    WHITESTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 0)),
    WHITEGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 0)),
    ORANGESTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 1)),
    ORANGESTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 1)),
    ORANGEGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 1)),
    MAGENTASTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 2)),
    MAGENTASTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 2)),
    MAGENTAGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 2)),
    LIGHTBLUESTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 3)),
    LIGHTBLUESTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 3)),
    LIGHTBLUEGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 3)),
    YELLOWSTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 4)),
    YELLOWSTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 4)),
    YELLOWGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 4)),
    LIMESTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 5)),
    LIMESTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 5)),
    LIMEGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 5)),
    PINKSTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 6)),
    PINKSTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 6)),
    PINKGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 6)),
    GRAYSTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 7)),
    GRAYSTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 7)),
    GRAYGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 7)),
    LIGHTGRAYSTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 8)),
    LIGHTGRAYSTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 8)),
    LIGHTGRAYGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 8)),
    CYANSTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 9)),
    CYANSTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 9)),
    CYANGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 9)),
    PURPLESTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 10)),
    PURPLESTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 10)),
    PURPLEGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 10)),
    BLUESTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 11)),
    BLUESTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 11)),
    BLUEGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 11)),
    BROWNSTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 12)),
    BROWNSTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 12)),
    BROWNGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 12)),
    GREENSTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 13)),
    GREENSTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 13)),
    GREENGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 13)),
    REDSTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 14)),
    REDSTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 14)),
    REDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 14)),
    BLACKSTAINEDPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 15)),
    BLACKSTAINEDGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 15)),
    BLACKGLASSPANE(ItemStack(Material.STAINED_GLASS_PANE, 1, 15)),

    CLAY(ItemStack(Material.CLAY)),
    HARDCLAY(ItemStack(Material.HARD_CLAY)),
    WHITESTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 0)),
    ORANGESTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 1)),
    MAGENTASTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 2)),
    LIGHTBLUESTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 3)),
    YELLOWSTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 4)),
    LIMESTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 5)),
    PINKSTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 6)),
    GRAYSTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 7)),
    LIGHTGRAYSTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 8)),
    CYANSTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 9)),
    PURPLESTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 10)),
    BLUESTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 11)),
    BROWNSTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 12)),
    GREENSTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 13)),
    REDSTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 14)),
    BLACKSTAINEDCLAY(ItemStack(Material.STAINED_CLAY, 1, 15)),

    DANDELION(ItemStack(Material.YELLOW_FLOWER, 1)),
    POPPY(ItemStack(Material.RED_ROSE, 1)),
    ORCHID(ItemStack(Material.RED_ROSE, 1, 1)),
    BLUEORCHID(ItemStack(Material.RED_ROSE, 1, 1)),
    ALLIUM(ItemStack(Material.RED_ROSE, 1, 2)),
    AZURE(ItemStack(Material.RED_ROSE, 1, 3)),
    AZUREBLUET(ItemStack(Material.RED_ROSE, 1, 3)),
    TULIP(ItemStack(Material.RED_ROSE, 1, 4)),
    REDTULIP(ItemStack(Material.RED_ROSE, 1, 4)),
    ORANGETULIP(ItemStack(Material.RED_ROSE, 1, 5)),
    WHITETULIP(ItemStack(Material.RED_ROSE, 1, 6)),
    PINKTULIP(ItemStack(Material.RED_ROSE, 1, 7)),
    DAISY(ItemStack(Material.RED_ROSE, 1, 8)),
    OXYEDAISY(ItemStack(Material.RED_ROSE, 1, 8)),

    SLAB(ItemStack(Material.STONE_SLAB2, 1)),
    STONESLAB(ItemStack(Material.STONE_SLAB2, 1)),
    SANDSTONESLAB(ItemStack(Material.STONE_SLAB2, 1, 1)),
    COBBLESLAB(ItemStack(Material.STONE_SLAB2, 1, 3)),
    COBBLESTONESLAB(ItemStack(Material.STONE_SLAB2, 1, 3)),
    BRICKSLAB(ItemStack(Material.STONE_SLAB2, 1, 4)),
    STONEBRICKSLAB(ItemStack(Material.STONE_SLAB2, 1, 5)),
    NETHERBRICKSLAB(ItemStack(Material.STONE_SLAB2, 1, 6)),
    NETHERSLAB(ItemStack(Material.STONE_SLAB2, 1, 6)),
    QUARTZSLAB(ItemStack(Material.STONE_SLAB2, 1, 7)),

    OAKSTAIRS(ItemStack(Material.WOOD_STAIRS, 1)),
    COBBLESTAIRS(ItemStack(Material.COBBLESTONE_STAIRS, 1)),
    BRICKSTAIRS(ItemStack(Material.BRICK_STAIRS, 1)),
    STONEBRICKSTAIRS(ItemStack(Material.SMOOTH_STAIRS, 1)),
    NETHERBRICKSTAIRS(ItemStack(Material.NETHER_BRICK_STAIRS, 1)),
    SPRUCESTAIRS(ItemStack(Material.SPRUCE_WOOD_STAIRS, 1)),
    BIRCHSTAIRS(ItemStack(Material.BIRCH_WOOD_STAIRS, 1)),
    JUNGLESTAIRS(ItemStack(Material.JUNGLE_WOOD_STAIRS, 1)),
    QUARTZSTAIRS(ItemStack(Material.QUARTZ_STAIRS, 1)),
    ACACIASTAIRS(ItemStack(Material.ACACIA_STAIRS, 1)),
    DARKOAKSTAIRS(ItemStack(Material.DARK_OAK_STAIRS, 1)),
    REDSANDSTONESTAIRS(ItemStack(Material.RED_SANDSTONE_STAIRS, 1)),

    STONEBUTTON(ItemStack(Material.STONE_BUTTON, 1)),
    WOODBUTTON(ItemStack(Material.WOOD_BUTTON, 1)),

    STONEPRESUREPLATE(ItemStack(Material.STONE_PLATE, 1)),
    STONEPLATE(ItemStack(Material.STONE_PLATE, 1)),
    WOODPRESUREPLATE(ItemStack(Material.WOOD_PLATE, 1)),
    WOODPLATE(ItemStack(Material.WOOD_PLATE, 1)),
    GOLDPRESUREPLATE(ItemStack(Material.GOLD_PLATE, 1)),
    GOLDPLATE(ItemStack(Material.GOLD_PLATE, 1)),
    IRONPRESUREPLATE(ItemStack(Material.IRON_PLATE, 1)),
    IRONPLATE(ItemStack(Material.IRON_PLATE, 1)),

    QUARTZBLOCK(ItemStack(Material.QUARTZ_BLOCK, 1)),
    CHISLEDQUARTZBLOCK(ItemStack(Material.QUARTZ_BLOCK, 1, 1)),
    PILLARQUARTZBLOCK(ItemStack(Material.QUARTZ_BLOCK, 1, 2)),

    // combat
    DIAMONDSWORD(ItemStack(Material.DIAMOND_SWORD, 1)),
    GOLDENDSWORD(ItemStack(Material.GOLD_SWORD, 1)),
    GOLDSWORD(ItemStack(Material.GOLD_SWORD, 1)),
    IRONSWORD(ItemStack(Material.IRON_SWORD, 1)),
    STONESWORD(ItemStack(Material.STONE_SWORD, 1)),
    WOODSWORD(ItemStack(Material.WOOD_SWORD, 1)),
    WOODENSWORD(ItemStack(Material.WOOD_SWORD, 1)),

    DIAMONDAXE(ItemStack(Material.DIAMOND_AXE, 1)),
    GOLDENDAXE(ItemStack(Material.GOLD_AXE, 1)),
    GOLDAXE(ItemStack(Material.GOLD_AXE, 1)),
    IRONAXE(ItemStack(Material.IRON_AXE, 1)),
    STONEAXE(ItemStack(Material.STONE_AXE, 1)),
    WOODAXE(ItemStack(Material.WOOD_AXE, 1)),
    WOODENAXE(ItemStack(Material.WOOD_AXE, 1)),

    DIAMONDPICKAXE(ItemStack(Material.DIAMOND_PICKAXE, 1)),
    GOLDENDPICKAXE(ItemStack(Material.GOLD_PICKAXE, 1)),
    GOLDPICKAXE(ItemStack(Material.GOLD_PICKAXE, 1)),
    IRONPICKAXE(ItemStack(Material.IRON_PICKAXE, 1)),
    STONEPICKAXE(ItemStack(Material.STONE_PICKAXE, 1)),
    WOODPICKAXE(ItemStack(Material.WOOD_PICKAXE, 1)),
    WOODENPICKAXE(ItemStack(Material.WOOD_PICKAXE, 1)),

    DIAMONDSHOVEL(ItemStack(Material.DIAMOND_SPADE, 1)),
    GOLDENDSHOVEL(ItemStack(Material.GOLD_SPADE, 1)),
    GOLDSHOVEL(ItemStack(Material.GOLD_SPADE, 1)),
    IRONSHOVEL(ItemStack(Material.IRON_SPADE, 1)),
    STONESHOVEL(ItemStack(Material.STONE_SPADE, 1)),
    WOODSHOVEL(ItemStack(Material.WOOD_SPADE, 1)),
    WOODENSHOVEL(ItemStack(Material.WOOD_SPADE, 1)),

    DIAMONDHOE(ItemStack(Material.DIAMOND_HOE, 1)),
    GOLDENDHOE(ItemStack(Material.GOLD_HOE, 1)),
    GOLDHOE(ItemStack(Material.GOLD_HOE, 1)),
    IRONHOE(ItemStack(Material.IRON_HOE, 1)),
    STONEHOE(ItemStack(Material.STONE_HOE, 1)),
    WOODHOE(ItemStack(Material.WOOD_HOE, 1)),
    WOODENHOE(ItemStack(Material.WOOD_HOE, 1)),

    LEATHERHELMET(ItemStack(Material.LEATHER_HELMET, 1)),
    LEATHERCHESTPLATE(ItemStack(Material.LEATHER_CHESTPLATE, 1)),
    LEATHERLEGGINGS(ItemStack(Material.LEATHER_LEGGINGS, 1)),
    LEATHERBOOTS(ItemStack(Material.LEATHER_BOOTS, 1)),

    GOLDHELMET(ItemStack(Material.GOLD_HELMET, 1)),
    GOLDENHELMET(ItemStack(Material.GOLD_HELMET, 1)),
    GOLDCHESTPLATE(ItemStack(Material.GOLD_CHESTPLATE, 1)),
    GOLDENCHESTPLATE(ItemStack(Material.GOLD_CHESTPLATE, 1)),
    GOLDLEGGINGS(ItemStack(Material.GOLD_LEGGINGS, 1)),
    GOLDENLEGGINGS(ItemStack(Material.GOLD_LEGGINGS, 1)),
    GOLDBOOTS(ItemStack(Material.GOLD_BOOTS, 1)),
    GOLDENBOOTS(ItemStack(Material.GOLD_BOOTS, 1)),

    IRONHELMET(ItemStack(Material.IRON_HELMET, 1)),
    IRONCHESTPLATE(ItemStack(Material.IRON_CHESTPLATE, 1)),
    IRONLEGGINGS(ItemStack(Material.IRON_LEGGINGS, 1)),
    IRONBOOTS(ItemStack(Material.IRON_BOOTS, 1)),

    CHAINMAILHELMET(ItemStack(Material.CHAINMAIL_HELMET, 1)),
    CHAINHELMET(ItemStack(Material.CHAINMAIL_HELMET, 1)),
    CHAINMAILCHESTPLATE(ItemStack(Material.CHAINMAIL_CHESTPLATE, 1)),
    CHAINCHESTPLATE(ItemStack(Material.CHAINMAIL_CHESTPLATE, 1)),
    CHAINMAILLEGGINGS(ItemStack(Material.CHAINMAIL_LEGGINGS, 1)),
    CHAINLEGGINGS(ItemStack(Material.CHAINMAIL_LEGGINGS, 1)),
    CHAINMAILBOOTS(ItemStack(Material.CHAINMAIL_BOOTS, 1)),
    CHAINBOOTS(ItemStack(Material.CHAINMAIL_BOOTS, 1)),

    DIAMONDHELMET(ItemStack(Material.DIAMOND_HELMET, 1)),
    DIAMONDCHESTPLATE(ItemStack(Material.DIAMOND_CHESTPLATE, 1)),
    DIAMONDLEGGINGS(ItemStack(Material.DIAMOND_LEGGINGS, 1)),
    DIAMONDBOOTS(ItemStack(Material.DIAMOND_BOOTS, 1)),

    // food stuff
    GOLDAPPLE(ItemStack(Material.GOLDEN_APPLE, 1)),
    GAPPLE(ItemStack(Material.GOLDEN_APPLE, 1)),
    CRAPPLE(ItemStack(Material.GOLDEN_APPLE, 1)),
    GOLDENAPPLE(ItemStack(Material.GOLDEN_APPLE, 1)),
    GODAPPLE(ItemStack(Material.GOLDEN_APPLE, 1, 1)),
    NOTCHAPPLE(ItemStack(Material.GOLDEN_APPLE, 1, 1)),
    RAWBEEF(ItemStack(Material.RAW_BEEF, 1)),
    BEEF(ItemStack(Material.RAW_BEEF, 1)),
    RAWMEAT(ItemStack(Material.RAW_BEEF, 1)),
    MEAT(ItemStack(Material.RAW_BEEF, 1)),
    STEAK(ItemStack(Material.COOKED_BEEF, 1)),
    COOKEDBEEF(ItemStack(Material.COOKED_BEEF, 1)),
    COOKEDMEAT(ItemStack(Material.COOKED_BEEF, 1)),
    RAWCHICKEN(ItemStack(Material.RAW_CHICKEN, 1)),
    COOKEDCHICKEN(ItemStack(Material.COOKED_CHICKEN, 1)),
    PORKCHOP(ItemStack(Material.PORK, 1)),
    COOKEDPORKCHOP(ItemStack(Material.GRILLED_PORK, 1)),
    COOKEDPORK(ItemStack(Material.GRILLED_PORK, 1)),
    RAWMUTTON(ItemStack(Material.MUTTON, 1)),
    COOKEDMUTTON(ItemStack(Material.COOKED_MUTTON, 1)),
    RAWRABBIT(ItemStack(Material.RABBIT, 1)),
    COOKEDRABBIT(ItemStack(Material.COOKED_RABBIT, 1)),
    FISH(ItemStack(Material.RAW_FISH, 1)),
    SALMON(ItemStack(Material.RAW_FISH, 1, 1)),
    CLOWNFISH(ItemStack(Material.RAW_FISH, 1, 2)),
    PUFFERFISH(ItemStack(Material.RAW_FISH, 1, 3)),
    COOKEDFISH(ItemStack(Material.COOKED_FISH, 1)),
    COOKEDSALMON(ItemStack(Material.COOKED_FISH, 1, 1)),
    BAKEDPOTATO(ItemStack(Material.BAKED_POTATO, 1)),
    POISONEDPOTATO(ItemStack(Material.POISONOUS_POTATO, 1)),
    POSIONPOTATO(ItemStack(Material.POISONOUS_POTATO, 1)),
    SPIDEREYE(ItemStack(Material.SPIDER_EYE, 1)),
    MUSHROOMSOUP(ItemStack(Material.MUSHROOM_SOUP, 1)),
    MUSHROOMSTEW(ItemStack(Material.MUSHROOM_SOUP, 1)),
    SOUP(ItemStack(Material.MUSHROOM_SOUP, 1)),
    RABBITSOUP(ItemStack(Material.MUSHROOM_SOUP, 1)),
    RABBITSTEW(ItemStack(Material.MUSHROOM_SOUP, 1)),
    PIE(ItemStack(Material.PUMPKIN_PIE, 1)),
    ROTTENFLESH(ItemStack(Material.ROTTEN_FLESH, 1)),

    // bucket
    WATER(ItemStack(Material.WATER_BUCKET, 1)),
    WATERBUCKET(ItemStack(Material.WATER_BUCKET, 1)),
    LAVA(ItemStack(Material.LAVA_BUCKET, 1)),
    LAVABUCKET(ItemStack(Material.LAVA_BUCKET, 1)),

    // misc
    DRAGONEGG(ItemStack(Material.DRAGON_EGG, 1)),
    MUSHROOM(ItemStack(Material.RED_MUSHROOM, 1)),
    REDMUSHROOM(ItemStack(Material.RED_MUSHROOM, 1)),
    BROWNMUSHROOM(ItemStack(Material.BROWN_MUSHROOM, 1)),
    MOSSSTONE(ItemStack(Material.MOSSY_COBBLESTONE, 1)),
    CRAFTINGTABLE(ItemStack(Material.WORKBENCH, 1)),
    PEARL(ItemStack(Material.ENDER_PEARL, 1)),
    ENDERPEARL(ItemStack(Material.ENDER_PEARL, 1)),
    LILLYPAD(ItemStack(Material.WATER_LILY, 1)),
    LILLY(ItemStack(Material.WATER_LILY, 1)),
    SNOW(ItemStack(Material.SNOW_BLOCK, 1)),
    SNOWBALL(ItemStack(Material.SNOW_BALL, 1)),
    CLAYBALL(ItemStack(Material.CLAY_BALL, 1)),
    MELON(ItemStack(Material.MELON_BLOCK, 1)),
    ENCHANTTABLE(ItemStack(Material.ENCHANTMENT_TABLE, 1)),
    ENDPORTAL(ItemStack(Material.ENDER_PORTAL_FRAME, 1)),
    ENDERCHEST(ItemStack(Material.ENDER_CHEST, 1)),
    TRAPPEDCHEST(ItemStack(Material.TRAPPED_CHEST, 1)),
    NETHERSTAR(ItemStack(Material.NETHER_STAR, 1)),
    TRIPWIRE(ItemStack(Material.TRIPWIRE_HOOK, 1)),
    TRIPWIREHOOK(ItemStack(Material.TRIPWIRE_HOOK, 1)),
    STICKYPISTON(ItemStack(Material.PISTON_STICKY_BASE, 1)),
    COBWEB(ItemStack(Material.WEB, 1)),
    DEADBUSH(ItemStack(Material.DEAD_BUSH, 1)),
    SNOWBLOCK(ItemStack(Material.SNOW_BLOCK, 1)),
    NAMETAG(ItemStack(Material.NAME_TAG, 1)),
    FLINTANDSTEEL(ItemStack(Material.FLINT_AND_STEEL, 1)),
    FLINTSTEEL(ItemStack(Material.FLINT_AND_STEEL, 1)),
    FNS(ItemStack(Material.FLINT_AND_STEEL, 1)),
    LIGHTER(ItemStack(Material.FLINT_AND_STEEL, 1)),
    FISHINGROD(ItemStack(Material.FISHING_ROD, 1)),
    ROD(ItemStack(Material.FISHING_ROD, 1)),
    MELONBLOCK(ItemStack(Material.MELON_BLOCK, 1)),
    WETSPONGE(ItemStack(Material.SPONGE, 1, 1)),
    LAPIS(ItemStack(Material.INK_SACK, 1, 4)),
    LAPISLAZULI(ItemStack(Material.INK_SACK, 1, 4)),
    COMMANDBLOCK(ItemStack(Material.COMMAND, 1, 0)),
    CMD(ItemStack(Material.COMMAND, 1, 0)),
    COMMAND_BLOCK(ItemStack(Material.COMMAND, 1, 0)),

    // colorful(gay) bed
    WHITEBED(ItemStack(Material.BED, 1, 0)),
    ORANGEBED(ItemStack(Material.BED, 1, 1)),
    MAGENTABED(ItemStack(Material.BED, 1, 2)),
    LIGHTBLUEBED(ItemStack(Material.BED, 1, 3)),
    YELLOWBED(ItemStack(Material.BED, 1, 4)),
    LIMEBED(ItemStack(Material.BED, 1, 5)),
    PINKBED(ItemStack(Material.BED, 1, 6)),
    GRAYBED(ItemStack(Material.BED, 1, 7)),
    LIGHTGRAYBED(ItemStack(Material.BED, 1, 8)),
    CYANBED(ItemStack(Material.BED, 1, 9)),
    PURPLEBED(ItemStack(Material.BED, 1, 10)),
    BLUEDBED(ItemStack(Material.BED, 1, 11)),
    BROWNBED(ItemStack(Material.BED, 1, 12)),
    GREENBED(ItemStack(Material.BED, 1, 13)),
    REDBED(ItemStack(Material.BED, 1, 14)),
    BLACKBED(ItemStack(Material.BED, 1, 15));


    companion object {
        /**
         * gets an itemStack by the 'human' name
         *
         * @param name = the 'human' item name
         * @param amount = the amount of item
         */
        fun getByName(name: String, amount: Int, damage: Int = 0): ItemStack? {
            var itemStack: ItemStack? = null

            try {
                itemStack = valueOf(name.uppercase()).itemStack
            } catch (e: Exception) {
            }

            if (itemStack == null) {
                if (Material.getMaterial(name.uppercase()) != null) {
                    itemStack = ItemStack(Material.getMaterial(name.uppercase()), amount)
                }
            }

            if (itemStack != null) {
                if (amount == -1) {
                    if (itemStack.maxStackSize > 1)
                        itemStack.amount = itemStack.maxStackSize
                    else
                        itemStack.amount = 1

                } else {
                    itemStack.amount = amount
                }

                // And apply the durability if needed...
                if (itemStack.durability == 0.toShort())
                    itemStack.durability = damage.toShort()

            }

            return itemStack
        }
    }
}